//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria
{
    public partial class SiteMaster
    {
        // ---- ContentPlaceHolders ----

        /// <summary>HeadContent – page-specific head tags and styles.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>TopbarActions – page-specific buttons in the topbar.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TopbarActions;

        /// <summary>MainContent – the primary page content region.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>PageScripts – page-specific script tags at bottom of body.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageScripts;

        // ---- Navigation panels ----

        /// <summary>pnlStudentNav – Student role navigation panel.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlStudentNav;

        /// <summary>pnlInstructorNav – Instructor role navigation panel (outer wrapper).</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructorNav;

        /// <summary>pnlInstructorPending – Status notice for Pending instructors.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructorPending;

        /// <summary>pnlInstructorRejected – Status notice for Rejected instructors.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructorRejected;

        /// <summary>pnlInstructorApprovedNav – Full instructor nav, shown when Approved.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructorApprovedNav;

        /// <summary>pnlInstructorLimitedNav – Restricted nav for Pending/Rejected instructors.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructorLimitedNav;

        /// <summary>pnlAdminNav – Admin role navigation panel.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdminNav;

        // ---- Sidebar profile literals ----

        /// <summary>litSidebarInitials – Two-character avatar initials in the sidebar profile.</summary>
        protected global::System.Web.UI.WebControls.Literal litSidebarInitials;

        /// <summary>litSidebarName – Full name shown in the sidebar profile.</summary>
        protected global::System.Web.UI.WebControls.Literal litSidebarName;

        /// <summary>litSidebarRole – Role label shown in the sidebar profile.</summary>
        protected global::System.Web.UI.WebControls.Literal litSidebarRole;

        // ---- Topbar controls ----

        /// <summary>litPageTitle – The main page title shown in the topbar.</summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>pnlPageSubtitle – Container for the optional topbar subtitle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPageSubtitle;

        /// <summary>litPageSubtitle – Optional subtitle beneath the page title.</summary>
        protected global::System.Web.UI.WebControls.Literal litPageSubtitle;

        /// <summary>pnlNotifications – The notification bell area in the topbar.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotifications;

        /// <summary>lnkNotifications – The notification bell anchor link.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNotifications;

        /// <summary>pnlNotifBadge – The unread count badge on the notification bell.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotifBadge;

        /// <summary>litNotifCount – Unread notification count text.</summary>
        protected global::System.Web.UI.WebControls.Literal litNotifCount;

        // ---- User menu ----

        /// <summary>pnlUserMenu – The user menu area in the topbar.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlUserMenu;

        /// <summary>litTopbarInitials – Two-character avatar initials in the topbar.</summary>
        protected global::System.Web.UI.WebControls.Literal litTopbarInitials;

        /// <summary>litTopbarName – User's name in the topbar user menu.</summary>
        protected global::System.Web.UI.WebControls.Literal litTopbarName;

        /// <summary>litTopbarRole – User's role label in the topbar user menu.</summary>
        protected global::System.Web.UI.WebControls.Literal litTopbarRole;

        /// <summary>lnkProfile – Profile link in the user dropdown.</summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkProfile;

        /// <summary>btnLogout – Log out button in the user dropdown.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        // ---- Footer controls ----

        /// <summary>pnlFooterStudentLinks – Student quick links in the footer.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFooterStudentLinks;

        /// <summary>pnlFooterInstructorLinks – Instructor quick links in the footer.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFooterInstructorLinks;

        /// <summary>pnlFooterAdminLinks – Admin quick links in the footer.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFooterAdminLinks;

        /// <summary>pnlFooterRole – Role badge container in the footer.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFooterRole;

        /// <summary>litFooterRole – Role name text inside the footer badge.</summary>
        protected global::System.Web.UI.WebControls.Literal litFooterRole;
    }
}
