//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Assignments
    {
        protected global::System.Web.UI.WebControls.Panel pnlCreateBtn;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassroom;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlAssignments;
        protected global::System.Web.UI.WebControls.Repeater rptAssignments;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlSubmissions;
        protected global::System.Web.UI.WebControls.Literal litAssignmentTitle;
        protected global::System.Web.UI.WebControls.Repeater rptSubmissions;
        protected global::System.Web.UI.WebControls.HiddenField hfSubmissionID;
        protected global::System.Web.UI.WebControls.HiddenField hfAssignmentIDFb;
        protected global::System.Web.UI.WebControls.TextBox txtFeedback;
        protected global::System.Web.UI.WebControls.TextBox txtGrade;
        protected global::System.Web.UI.WebControls.Button btnSaveFeedback;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassroomCreate;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtADesc;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O3;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O4;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O3;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O4;
        protected global::System.Web.UI.WebControls.TextBox txtAQ3;
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
