//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Assignments
    {
        // ── Section 1 — Assignment list ──────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlCreateBtn;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassroom;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlAssignments;
        protected global::System.Web.UI.WebControls.Repeater rptAssignments;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        // ── Section 2 — Submitted students ──────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlSection2;
        protected global::System.Web.UI.WebControls.Literal litSection2Title;
        protected global::System.Web.UI.WebControls.LinkButton btnBackToAssignments;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedAssignmentID;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedAssignmentTitle;
        protected global::System.Web.UI.WebControls.Panel pnlStudentList;
        protected global::System.Web.UI.WebControls.Repeater rptStudents;
        protected global::System.Web.UI.WebControls.Panel pnlNoStudents;

        // ── Section 3 — Per-student detail ───────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlSection3;
        protected global::System.Web.UI.WebControls.LinkButton btnBackToStudents;
        protected global::System.Web.UI.WebControls.HiddenField hfDetailStudentID;
        protected global::System.Web.UI.WebControls.HiddenField hfDetailStudentName;
        protected global::System.Web.UI.WebControls.HiddenField hfDetailSubmittedAt;
        protected global::System.Web.UI.WebControls.HiddenField hfSubmissionID;
        protected global::System.Web.UI.WebControls.HiddenField hfAssignmentIDFb;
        protected global::System.Web.UI.WebControls.HiddenField hfExistingFeedback;
        protected global::System.Web.UI.WebControls.HiddenField hfExistingGrade;
        protected global::System.Web.UI.WebControls.Literal litDetailStudentName;
        protected global::System.Web.UI.WebControls.Literal litDetailAssignmentTitle;
        protected global::System.Web.UI.WebControls.Literal litDetailSubmittedAt;
        protected global::System.Web.UI.WebControls.Repeater rptDetail;

        // ── Feedback modal ────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox txtFeedback;
        protected global::System.Web.UI.WebControls.TextBox txtGrade;
        protected global::System.Web.UI.WebControls.Button btnSaveFeedback;

        // ── Create assignment modal ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList ddlClassroomCreate;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtADesc;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O3;
        protected global::System.Web.UI.WebControls.TextBox txtAQ1O4;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O1;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O2;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O3;
        protected global::System.Web.UI.WebControls.TextBox txtAQ2O4;
        protected global::System.Web.UI.WebControls.TextBox txtAQ3;
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
