//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Challenges
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlChallenges;
        protected global::System.Web.UI.WebControls.Repeater rptChallenges;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.TextBox txtChTitle;
        protected global::System.Web.UI.WebControls.TextBox txtChDesc;
        protected global::System.Web.UI.WebControls.TextBox txtChXP;
        protected global::System.Web.UI.WebControls.TextBox txtChStart;
        protected global::System.Web.UI.WebControls.TextBox txtChEnd;
        protected global::System.Web.UI.WebControls.Button btnCreateCh;
        protected global::System.Web.UI.WebControls.Panel pnlManageQuestions;
        protected global::System.Web.UI.WebControls.Literal litManageChTitle;
        protected global::System.Web.UI.WebControls.TextBox txtChQText;
        protected global::System.Web.UI.WebControls.TextBox txtChQPoints;
        protected global::System.Web.UI.WebControls.TextBox txtChQTime;
        protected global::System.Web.UI.WebControls.Repeater rptChOptions;
        protected global::System.Web.UI.WebControls.Button btnAddChQuestion;
        protected global::System.Web.UI.WebControls.Panel pnlChQuestionsList;
        protected global::System.Web.UI.WebControls.Repeater rptChQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlNoChQuestions;
    }
}
