//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Classrooms
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlClassrooms;
        protected global::System.Web.UI.WebControls.Repeater rptClassrooms;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlStudents;
        protected global::System.Web.UI.WebControls.Literal litSelectedClassroom;
        protected global::System.Web.UI.WebControls.Repeater rptStudents;
        protected global::System.Web.UI.WebControls.TextBox txtClassName;
        protected global::System.Web.UI.WebControls.TextBox txtInviteCode;
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
