//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Classrooms
    {
        // ── Section 1 — Classroom cards ─────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlClassrooms;
        protected global::System.Web.UI.WebControls.Repeater rptClassrooms;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        // ── Section 2 — Chat room ────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlChatRoom;
        protected global::System.Web.UI.WebControls.Literal litChatRoomName;
        protected global::System.Web.UI.WebControls.Literal litSidebarName;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseChat;
        protected global::System.Web.UI.WebControls.HiddenField hfChatClassroomID;

        // Chat tab
        protected global::System.Web.UI.WebControls.Literal litMessages;
        protected global::System.Web.UI.WebControls.TextBox txtMessage;
        protected global::System.Web.UI.WebControls.Button btnSend;

        // Files tab
        protected global::System.Web.UI.WebControls.Literal litFiles;

        // Assignments tab
        protected global::System.Web.UI.WebControls.Literal litAssignments;

        // Members tab
        protected global::System.Web.UI.WebControls.Literal litMembers;

        // ── Create Classroom Modal ────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox txtClassName;
        protected global::System.Web.UI.WebControls.TextBox txtInviteCode;
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
