//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Consultations
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSlots;
        protected global::System.Web.UI.WebControls.Repeater rptSlots;
        protected global::System.Web.UI.WebControls.Panel pnlNoSlots;
        protected global::System.Web.UI.WebControls.Panel pnlBookings;
        protected global::System.Web.UI.WebControls.Repeater rptBookings;
        protected global::System.Web.UI.WebControls.Panel pnlNoBookings;
        protected global::System.Web.UI.WebControls.TextBox txtSlotDate;
        protected global::System.Web.UI.WebControls.TextBox txtStartTime;
        protected global::System.Web.UI.WebControls.TextBox txtEndTime;
        protected global::System.Web.UI.WebControls.Button btnAddSlot;
    }
}
