//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litWelcomeName;
        protected global::System.Web.UI.WebControls.Panel pnlHeaderActions;
        protected global::System.Web.UI.WebControls.Panel pnlPendingNotice;
        protected global::System.Web.UI.WebControls.Panel pnlRejectedNotice;
        protected global::System.Web.UI.WebControls.Panel pnlStats;
        protected global::System.Web.UI.WebControls.Literal litClassroomCount;
        protected global::System.Web.UI.WebControls.Literal litModuleCount;
        protected global::System.Web.UI.WebControls.Literal litStudentCount;
        protected global::System.Web.UI.WebControls.Literal litPendingAssignments;
        protected global::System.Web.UI.WebControls.Panel pnlClassroomList;
        protected global::System.Web.UI.WebControls.Repeater rptClassrooms;
        protected global::System.Web.UI.WebControls.Panel pnlNoClassrooms;
        protected global::System.Web.UI.WebControls.Panel pnlSubmissions;
        protected global::System.Web.UI.WebControls.Repeater rptSubmissions;
        protected global::System.Web.UI.WebControls.Panel pnlNoSubmissions;
        protected global::System.Web.UI.WebControls.Panel pnlRecentNotif;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
    }
}
