//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Discussions
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlThreads;
        protected global::System.Web.UI.WebControls.Repeater rptThreads;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlThread;
        protected global::System.Web.UI.WebControls.Literal litThreadTitle;
        protected global::System.Web.UI.WebControls.Literal litThreadBody;
        protected global::System.Web.UI.WebControls.Literal litThreadMeta;
        protected global::System.Web.UI.WebControls.Panel pnlReplies;
        protected global::System.Web.UI.WebControls.Repeater rptReplies;
        protected global::System.Web.UI.WebControls.HiddenField hfThreadID;
        protected global::System.Web.UI.WebControls.TextBox txtReply;
        protected global::System.Web.UI.WebControls.Button btnReply;
        protected global::System.Web.UI.WebControls.TextBox txtThreadTitle;
        protected global::System.Web.UI.WebControls.TextBox txtThreadBody;
        protected global::System.Web.UI.WebControls.Button btnCreateThread;
    }
}
