//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Materials
    {
        protected global::System.Web.UI.WebControls.Panel pnlUploadBtn;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubTopic;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlMaterials;
        protected global::System.Web.UI.WebControls.Repeater rptMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubTopicUpload;
        protected global::System.Web.UI.WebControls.FileUpload fuMaterial;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Button btnUpload;
    }
}
