//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litLicenseBadge;
        protected global::System.Web.UI.WebControls.Literal litQualification;
        protected global::System.Web.UI.WebControls.Literal litLicenseStatus;
        protected global::System.Web.UI.WebControls.Literal litApprovedAt;
        protected global::System.Web.UI.WebControls.Literal litMemberSince;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.Literal litEmailReadonly;
        protected global::System.Web.UI.WebControls.TextBox txtQualification;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        protected global::System.Web.UI.WebControls.Panel pnlReportSuccess;
        protected global::System.Web.UI.WebControls.Literal litReportSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlReportError;
        protected global::System.Web.UI.WebControls.Literal litReportError;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportType;
        protected global::System.Web.UI.WebControls.TextBox txtReportReason;
        protected global::System.Web.UI.WebControls.Button btnSubmitReport;
    }
}
