//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class Questions
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlSubTopic;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlQuestions;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
