//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Instructor
{
    public partial class SubTopics
    {
        protected global::System.Web.UI.WebControls.Literal litModuleContext;
        protected global::System.Web.UI.WebControls.Panel pnlAddBtn;
        protected global::System.Web.UI.WebControls.DropDownList ddlModule;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSubTopics;
        protected global::System.Web.UI.WebControls.Repeater rptSubTopics;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.DropDownList ddlModuleCreate;
        protected global::System.Web.UI.WebControls.TextBox txtSubTopicName;
        protected global::System.Web.UI.WebControls.TextBox txtContent;
        protected global::System.Web.UI.WebControls.TextBox txtOrderIndex;
        protected global::System.Web.UI.WebControls.TextBox txtSTXP;
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
