//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Student
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litWelcomeName;
        protected global::System.Web.UI.WebControls.Literal litTotalXP;
        protected global::System.Web.UI.WebControls.Literal litModulesCompleted;
        protected global::System.Web.UI.WebControls.Literal litBadgesEarned;
        protected global::System.Web.UI.WebControls.Literal litClassroomsJoined;
        protected global::System.Web.UI.WebControls.Panel pnlContinueLearning;
        protected global::System.Web.UI.WebControls.Repeater rptInProgress;
        protected global::System.Web.UI.WebControls.Panel pnlNoContinue;
        protected global::System.Web.UI.WebControls.Panel pnlRecentXP;
        protected global::System.Web.UI.WebControls.Repeater rptRecentXP;
        protected global::System.Web.UI.WebControls.Panel pnlNoXP;
        protected global::System.Web.UI.WebControls.Panel pnlRecentNotif;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
    }
}
