<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class AuditLogs
    {
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.DropDownList ddlTable;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptLogs;
=======
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Repeater rptAuditLog;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
