<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class Challenges
    {
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtXPReward;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvXP;
        protected global::System.Web.UI.WebControls.RangeValidator rvXP;
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStart;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEnd;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Literal litActiveCount;
        protected global::System.Web.UI.WebControls.Literal litUpcomingCount;
        protected global::System.Web.UI.WebControls.Literal litEndedCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptChallenges;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
=======
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.TextBox txtGCTitle;
        protected global::System.Web.UI.WebControls.TextBox txtGCDesc;
        protected global::System.Web.UI.WebControls.TextBox txtGCXP;
        protected global::System.Web.UI.WebControls.TextBox txtGCStart;
        protected global::System.Web.UI.WebControls.TextBox txtGCEnd;
        protected global::System.Web.UI.WebControls.Button btnCreateGlobalChallenge;
        protected global::System.Web.UI.WebControls.Panel pnlGlobalChallenges;
        protected global::System.Web.UI.WebControls.Repeater rptGlobalChallenges;
        protected global::System.Web.UI.WebControls.Panel pnlNoGlobalChallenges;
        protected global::System.Web.UI.WebControls.Panel pnlManageQuestions;
        protected global::System.Web.UI.WebControls.Literal litManageGCTitle;
        protected global::System.Web.UI.WebControls.TextBox txtGCQText;
        protected global::System.Web.UI.WebControls.TextBox txtGCQPoints;
        protected global::System.Web.UI.WebControls.TextBox txtGCQTime;
        protected global::System.Web.UI.WebControls.Repeater rptGCOptions;
        protected global::System.Web.UI.WebControls.Button btnAddGCQuestion;
        protected global::System.Web.UI.WebControls.Panel pnlGCQuestionsList;
        protected global::System.Web.UI.WebControls.Repeater rptGCQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlNoGCQuestions;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
    }
}
