<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litWelcomeName;
        protected global::System.Web.UI.WebControls.Literal litTotalUsers;
        protected global::System.Web.UI.WebControls.Literal litPendingApprovals;
        protected global::System.Web.UI.WebControls.Literal litOpenReports;
        protected global::System.Web.UI.WebControls.Literal litPublishedModules;
        protected global::System.Web.UI.WebControls.Literal litPendingFunRooms;
        protected global::System.Web.UI.WebControls.Literal litActiveChallenges;
        protected global::System.Web.UI.WebControls.Literal litBossFightRooms;
        protected global::System.Web.UI.WebControls.Literal litTotalStudents;
        protected global::System.Web.UI.WebControls.Panel pnlPendingAlert;
        protected global::System.Web.UI.WebControls.Literal litPendingAlertText;
        protected global::System.Web.UI.WebControls.Panel pnlPendingInstructors;
        protected global::System.Web.UI.WebControls.Repeater rptPendingInstructors;
        protected global::System.Web.UI.WebControls.Panel pnlNoPendingInstructors;
        protected global::System.Web.UI.WebControls.Panel pnlRecentReports;
        protected global::System.Web.UI.WebControls.Repeater rptRecentReports;
        protected global::System.Web.UI.WebControls.Panel pnlNoReports;
        protected global::System.Web.UI.WebControls.Panel pnlFunRoomsSection;
        protected global::System.Web.UI.WebControls.Repeater rptPendingFunRooms;
        protected global::System.Web.UI.WebControls.Panel pnlAuditLog;
        protected global::System.Web.UI.WebControls.Repeater rptAuditLog;
        protected global::System.Web.UI.WebControls.Panel pnlNoAudit;
=======
﻿namespace CloudPhoria.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litTotalStudents;
        protected global::System.Web.UI.WebControls.Literal litTotalInstructors;
        protected global::System.Web.UI.WebControls.Literal litPendingCount;
        protected global::System.Web.UI.WebControls.Literal litTotalModules;
        protected global::System.Web.UI.WebControls.Literal litOpenReports;
        protected global::System.Web.UI.WebControls.Literal litBannedCount;
        protected global::System.Web.UI.WebControls.Literal litGlobalChallengeCount;
        protected global::System.Web.UI.WebControls.Literal litTotalClassrooms;
        protected global::System.Web.UI.WebControls.Literal litPendingCount2;
        protected global::System.Web.UI.WebControls.Literal litOpenReports2;
        protected global::System.Web.UI.WebControls.Panel pnlRecentActivity;
        protected global::System.Web.UI.WebControls.Repeater rptRecentActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
    }
}
