<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class InstructorApprovals
    {
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptInstructors;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
=======
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlPendingInstructors;
        protected global::System.Web.UI.WebControls.Repeater rptPendingInstructors;
        protected global::System.Web.UI.WebControls.Panel pnlNoPending;
        protected global::System.Web.UI.WebControls.Repeater rptAllInstructors;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
    }
}
