<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class Notifications
    {
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Button btnMarkAllRead;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litUnreadCount;
        protected global::System.Web.UI.WebControls.Literal litTotalCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
=======
        protected global::System.Web.UI.WebControls.Panel pnlMarkAllBtn;
        protected global::System.Web.UI.WebControls.Button btnMarkAll;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlNotifications;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
