//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Admin
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litJoined;
        protected global::System.Web.UI.WebControls.Literal litActionsCount;
        protected global::System.Web.UI.WebControls.Literal litApprovedCount;
        protected global::System.Web.UI.WebControls.Literal litReportsReviewed;
        protected global::System.Web.UI.WebControls.Literal litBossCreated;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPwd;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCurrentPwd;
        protected global::System.Web.UI.WebControls.TextBox txtNewPwd;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewPwd;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPwd;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmPwd;
        protected global::System.Web.UI.WebControls.CompareValidator cvPasswords;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
