//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Admin
{
    public partial class Reports
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litOpenCount;
        protected global::System.Web.UI.WebControls.Literal litReviewedCount;
        protected global::System.Web.UI.WebControls.Literal litActionCount;
        protected global::System.Web.UI.WebControls.Literal litDismissedCount;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptReports;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
