<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class Reports
    {
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litOpenCount;
        protected global::System.Web.UI.WebControls.Literal litReviewedCount;
        protected global::System.Web.UI.WebControls.Literal litActionCount;
        protected global::System.Web.UI.WebControls.Literal litDismissedCount;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptReports;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
=======
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Panel pnlReports;
        protected global::System.Web.UI.WebControls.Repeater rptReports;
        protected global::System.Web.UI.WebControls.Panel pnlNoReports;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
    }
}
