<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

=======
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
namespace CloudPhoria.Admin
{
    public partial class Users
    {
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Literal litResultCount;
        protected global::System.Web.UI.WebControls.Panel pnlUsers;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Panel pnlNoUsers;
=======
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlRoleFilter;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewUserRole;
        protected global::System.Web.UI.WebControls.TextBox txtNewUserName;
        protected global::System.Web.UI.WebControls.TextBox txtNewUserEmail;
        protected global::System.Web.UI.WebControls.TextBox txtNewUserPassword;
        protected global::System.Web.UI.WebControls.Button btnCreateUser;
>>>>>>> 726bdf5aeacf983cac6697131a8d378b065b2cac
    }
}
