//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Guest
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litPathwayCount;
        protected global::System.Web.UI.WebControls.Literal litModuleCount;
        protected global::System.Web.UI.WebControls.Literal litPracticeCount;
        protected global::System.Web.UI.WebControls.Panel  pnlPathways;
        protected global::System.Web.UI.WebControls.Panel  pnlFeaturedModules;
    }
}
