//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Guest
{
    public partial class Pathways
    {
        protected global::System.Web.UI.WebControls.Panel  pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel  pnlPathwayGrid;
    }
}
