//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPhoria.Guest
{
    public partial class Practice
    {
        protected global::System.Web.UI.WebControls.Panel       pnlError;
        protected global::System.Web.UI.WebControls.Literal     litError;
        protected global::System.Web.UI.WebControls.DropDownList ddlModules;
        protected global::System.Web.UI.WebControls.Button      btnStart;
        protected global::System.Web.UI.WebControls.Panel       pnlNoQuestions;
        protected global::System.Web.UI.WebControls.Panel       pnlQuiz;
        protected global::System.Web.UI.WebControls.Panel       pnlQuizContent;
    }
}
